variables:
    GIT_STRATEGY: clone
    BUILD_TESTING: "NO"
    CUDA_AVAILABLE: "NO"


Ubuntu-gcc9-superbuild:
    stage: test
    tags:
      - linux
      - docker
      - gpu
    image: andreasga/cbctrecon:gcc-9-x86_64
    script:
      - export CC=/usr/bin/gcc-9
      - export CXX=/usr/bin/g++-9
      - export CXXFLAGS = -std=c++17 -I/usr/include -I/usr/include/tbb -fopenmp-simd \
      - export LDFLAGS = -L/usr/lib/x86_64-linux-gnu -ltbb \
      - ./ci/ci.sh

Ubuntu-gcc8-CUDA:
    stage: test
    tags:
      - linux
      - docker
      - cuda
      - gpu
    image: andreasga/cbctrecon:gcc-8-CUDA-x86_64
    variables:
      CUDA_AVAILABLE: "YES"
      COVERAGE: "YES"
    script:
      - export CC=/usr/bin/gcc-8
      - export CXX=/usr/bin/g++-8
      - ./ci/ci.sh

Ubuntu-gcc9-coverage-prebuild-deps:
    stage: test
    tags:
      - linux
      - docker
      - gpu
    image: andreasga/cbctrecon:gcc-9-x86_64-libDCMTK-ITKv5-RTK
    variables:
      COVERAGE: "YES"
    script:
      - export CC=/usr/bin/gcc-9
      - export CXX=/usr/bin/g++-9
      - export CXXFLAGS = -std=c++17 -I/usr/include -I/usr/include/tbb -fopenmp-simd \
      - export LDFLAGS = -L/usr/lib/x86_64-linux-gnu -ltbb \
      - ./ci/ci.sh


#Ubuntu-clang6:
#    stage: test
#    tags:
#      - linux
#      - docker
#      - gpu
#    image: andreasga/cbctrecon:clang-6-x86_64
#    script:
#      - export CC=clang
#      - export CXX=clang++
#      - ./ci/ci.sh

Ubuntu-clang9-prebuild-deps:
    stage: test
    tags:
      - linux
      - docker
      - gpu
    image: andreasga/cbctrecon:clang-9-x86_64-libDCMTK-ITKv5-RTK
    script:
      - export CC=clang
      - export CXX=clang++
      - ./ci/ci.sh

