#------------------------------------------------------------------------------
#  AppVeyor Continous Integration (CI) configuration file
#
# Configures a Windows-like environment for building CbctRecon on AppVeyor.
#


# Windows Server 2012 R2 (x64) <== Appveyor default image
# Visual Studio 2015

# os: expands the build matrix to include multiple os's
os:
  - Windows Server 2012

# Target platform
platform:
  - x64

# Only clone the top level commit; don't bother with history
shallow_clone: true

environment:
  # Environment variables
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  DCMTK_VERSION: DCMTK-3.6.3
  DCMTK_SOURCE_DIR: "C:/projects/DCMTK"
  DCMTK_BINARY_DIR: "C:/projects/DCMTK-build"
  ITK_VERSION: v4.13.1
  ITK_SOURCE_DIR: "C:/projects/ITK"
  ITK_BINARY_DIR: "C:/projects/ITK-build"
  FFTW_DIR: "C:/projects/cbctrecon/bin/fftw"
  OPENCL_DIR: "C:/projects/cbctrecon/bin/opencl"
  BUILD_TYPE: Release
  CTEST_SOURCE_DIRECTORY: "%APPVEYOR_BUILD_FOLDER%"
  CTEST_BINARY_DIRECTORY: "%APPVEYOR_BUILD_FOLDER%/build"
  CTEST_CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
  CTEST_TEST_TIMEOUT: "300"
  CTEST_BUILD_CONFIGURATION: Release
  CTEST_CONFIGURATION_TYPE: Release

  # Build matrix. (defines different configuration for multiple jobs)
  matrix:
    - GENERATOR: "%CTEST_CMAKE_GENERATOR%"

  global:
    OPENCL_ROOT: "%APPVEYOR_BUILD_FOLDER%\\bin\\opencl"
    FFTW_ROOT: "%APPVEYOR_BUILD_FOLDER%\\bin\\fftw"
    OPENCL_REGISTRY: "https://www.khronos.org/registry/cl"


init:
  - echo init step
  - cmake --version
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%

# We need to create an opencl import library that cbctrecon can link against
# Vendor based OpenCL packages are hard to use because of download size, registration requirements
# and unattended installs not well supported
install:
  - echo Installing OpenCL
  - ps: mkdir $env:OPENCL_ROOT
  - ps: pushd $env:OPENCL_ROOT
  # { #1: $env:OPENCL_ROOT
  - ps: $opencl_registry = $env:OPENCL_REGISTRY
  # This downloads the source to the Khronos ICD library
  - git clone --depth 1 https://github.com/KhronosGroup/OpenCL-ICD-Loader.git
  - ps: mv ./OpenCL-ICD-Loader/* .
  # This downloads all the opencl header files
  # The cmake build files expect a directory called inc
  - git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers.git include
  - ps: cp -r ./include/* ./inc/
  - ps: ls ./include/CL
  # Create the static import lib in a directory called lib, so findopencl() will find it
  - ps: mkdir lib
  - ps: pushd lib
  #   { #2: $env:OPENCL_ROOT/lib
  - cmake -G "NMake Makefiles" ..
  - nmake
  - ps: mkdir x64; cp OpenCL.lib x64\
  - ps: popd
  #   } #2 back to $env:OPENCL_ROOT
  - ps: popd
  # } #1 back to %APPVEYOR_BUILD_FOLDER%

  - echo Installing FFTW
  - ps: mkdir $env:FFTW_ROOT
  - ps: pushd $env:FFTW_ROOT
  # This downloads the windows 64-bit pre-compiled dlls
  - ps: wget ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll64.zip -OutFile fftw-3.3.4-dll64.zip
  - ps: 7z x fftw-3.3.4-dll64.zip
  #  - ps: pushd fftw-3.3.4-dll64
  - ps: lib /machine:x64 /def:libfftw3-3.def
  - ps: lib /machine:x64 /def:libfftw3f-3.def
  - ps: lib /machine:x64 /def:libfftw3l-3.def
  - ps: ls

cache:
  # Caching DCMTK source and build tree
  - '%DCMTK_SOURCE_DIR% -> .appveyor_clear_cache'
  - '%DCMTK_BINARY_DIR% -> .appveyor_clear_cache'
  # Caching ITK source and build tree
  - '%ITK_SOURCE_DIR% -> .appveyor_clear_cache'
  - '%ITK_BINARY_DIR% -> .appveyor_clear_cache'

build:
  parallel: true
  verbosity: minimal

before_build:
  # For CMake to find OpenCL:
  - ps: $env:AMDAPPSDKROOT = "$env:OPENCL_ROOT"
  - ps: dir $env:AMDAPPSDKROOT; dir $env:AMDAPPSDKROOT/lib; dir $env:AMDAPPSDKROOT/include;
  - cd "%APPVEYOR_BUILD_FOLDER%" & mkdir build & cd build
  ######## DCMTK ########
  # Checkout DCMTK source tree
  - if not exist "%DCMTK_SOURCE_DIR%" (
      cd C:/projects/ &
      git clone --depth 1 --branch %DCMTK_VERSION% https://github.com/DCMTK/DCMTK.git DCMTK
    )
  - if not exist "%DCMTK_BINARY_DIR%" (
      cd C:/projects/ &
      mkdir "%DCMTK_BINARY_DIR%"
    )
  # Build DCMTK
  - if not exist "%DCMTK_BINARY_DIR%/lib/Release/dcmimage.lib" (
      cd "%DCMTK_BINARY_DIR%" &
      cmake -G "%GENERATOR%" -DBUILD_TESTING:BOOL=OFF ../DCMTK -DBUILD_EXAMPLES=OFF -DDCMTK_WITH_DOXYGEN=OFF -DDCMTK_ENABLE_CXX11=ON -DDCMTK_ENABLE_STL=ON -DDCMTK_OVERWRITE_WIN32_COMPILER_FLAGS=OFF -DDCMTK_WITH_XML=OFF -DDCMTK_WITH_PNG=OFF -DDCMTK_WITH_TIFF=OFF -DDCMTK_WITH_OPENSSL=OFF -DDCMTK_WITH_SNDFILE=OFF -DDCMTK_WITH_ICONV=OFF &
      cmake --build . --config %BUILD_TYPE% &
      exit 1
    )
  ######## ITK ########
  # Checkout ITK source tree
  - if not exist "%ITK_SOURCE_DIR%" (
      cd C:/projects/ &
      git clone --depth 1 --branch %ITK_VERSION% https://github.com/InsightSoftwareConsortium/ITK.git ITK
    )
  - if not exist "%ITK_BINARY_DIR%" (
      cd C:/projects/ &
      mkdir "%ITK_BINARY_DIR%"
    )
  # Build ITK
  - if not exist "%ITK_BINARY_DIR%/Modules/Remote/RTK/RTKConfig.cmake" (
      cd "%ITK_BINARY_DIR%" &
      cp "%APPVEYOR_BUILD_FOLDER%/External/patches/ExternalRTK.remote.cmake" "%ITK_SOURCE_DIR%/Modules/Remote/" &
      cmake -G "%GENERATOR%" -DBUILD_TESTING:BOOL=OFF ../ITK -DBUILD_EXAMPLES=OFF -DModule_ITKReview=ON -DModule_RTK=ON -DITK_USE_SYSTEM_FFTW=ON -DITK_USE_FFTWF=ON -DFFTWF_LIB="%FFTW_DIR%/libfftw3f-3.lib" -DITK_USE_FFTWD=ON -DFFTWD_LIB="%FFTW_DIR%/libfftw3-3.lib" -DFFTW_INCLUDE_PATH="%FFTW_DIR%" -DFFTW_INCLUDE_DIR="%FFTW_DIR%" -DITK_USE_GPU=ON -DITK_BUILD_DEFAULT_MODULES=OFF -DOPENCL_INCLUDE_DIRS="%OPENCL_DIR%/include" -DOPENCL_LIBRARIES="%OPENCL_DIR%/lib/x64/OpenCL.lib"  -DOPENCL_ROOT_DIR="%OPENCL_DIR%" -DITK_USE_SYSTEM_DCMTK=ON -DDCMTK_DIR="%DCMTK_BINARY_DIR%" -DModule_ITKMathematicalMorphology=ON -DRTK_BUILD_APPLICATIONS=OFF -DRTK_TIME_EACH_FILTER=ON -DRTK_USE_CUDA=OFF &
      cmake --build . --config %BUILD_TYPE% &
      exit 1
    )
  # Build ITK again if necessary
  - if not exist "%ITK_BINARY_DIR%/lib/%BUILD_TYPE%/itkRTK-4.13.lib" (
      cd "%ITK_BINARY_DIR%" &
      cmake ../ITK -DModule_RTK=ON &
      cmake --build . --config %BUILD_TYPE% &
      exit 1
    )

build_script:
  - git config --global user.email "andreasga22@gmail.com"
  - git config --global user.name "Andreas Gravgaard Andersen"
  # Configure CbctRecon and dependencies
  - cmake -G"%CTEST_CMAKE_GENERATOR%" "%APPVEYOR_BUILD_FOLDER%" -DBUILD_TESTING=OFF -DUSE_CUDA=OFF -DCBCTRECON_BUILD_TESTS=ON -DUSE_TINYREFL=OFF -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/build/" -DQt5_DIR="C:/Qt/5.11.1/msvc2015_64/lib/cmake/Qt5" -DITK_DIR="%ITK_BINARY_DIR%" -DDCMTK_DIR="%DCMTK_BINARY_DIR%" -DUSE_SYSTEM_ITK=ON -DUSE_SYSTEM_DCMTK=ON
  # Fetch ExternalData. (Retried up to 3 times if network errors occured) <- TODO:this step must be added!!
  # Build CbctRecon (and all targets, necessary for packaging)
  - cmake --build . --config %BUILD_TYPE%
  # - cmake "%APPVEYOR_BUILD_FOLDER%" may be necessary when tinyrefl supports windows
  - cmake --build . --config %BUILD_TYPE% --target CbctRecon_test
  # Run CbctRecon_test
  - ctest -V -C %BUILD_TYPE%
  # Create .msi
  - cpack -C %BUILD_TYPE%
  - move CbctRecon-*.msi %APPVEYOR_BUILD_FOLDER%

test: off

artifacts:
  - path: 'CbctRecon-*.msi'
    name: binary_msi

# Appveyor will push the artifacts it has saved to GitLab 'releases' tab
deploy:
  - provider: GitHub
    repository: agravgaard/CbctRecon
    description: "Windows installer from AppVeyor CI"
    auth_token:
      secure: Wcahfcb8RTeiEypo/pM0fLnLU+Pd7Hd2UV1tQbJfihQEayaz/Ucb0am78msCC0yy
    artifact: /.*\.msi/
    draft: true
    prerelease: true
    on:
      branch: master
    # appveyor_repo_tag: true
